name: gomodd:1.23.4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_ALI_PASSWORD }}" | docker login --username="${{ secrets.DOCKER_ALI_USERNAME }}" registry.cn-hangzhou.aliyuncs.com --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/lawyer01/gomodd::1.23.4
    - name: Push the Docker image
      run: docker push registry.cn-hangzhou.aliyuncs.com/lawyer01/gomodd::1.23.4
      
    # steps:
    # - uses: actions/checkout@v4
    # - name: Log in to Docker Hub
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    # - name: Build the Docker image
    #   # run: docker build . --file Dockerfile --tag my-dockerhub-username/my-image-name:1.23.4
    #   run: docker build . --file Dockerfile --tag anhao1226/gomodd:1.23.4
    # - name: Push the Docker image
    #   # run: docker push my-dockerhub-username/my-image-name:1.23.4
    #   run: docker push anhao1226/gomodd:1.23.4


# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
